language: python
cache:
- pip
python:
- '2.7'
- '3.3'
- '3.6'
install:
- pip install -r requirements.txt
script:
- python -m pytest
deploy:
  provider: pypi
  user: mwvaughn
  password:
    secure: el7l2LdOOfsTIIi4G5uHxJ/1FGJDlMyV53lop1IQdetoAnXu9ZR+WemELq7FyxNBTvvQCn86yL4RpRM75Bp347hI9QheE2QxJWU38wwODL59bwgH0kL0iBcjn4g+wU0+IQhRZxtYYMfEZaEZH0j6eqg8pWgqTGuyftdaIWzKr2yhwdbqwSkkBnFmlaOTvDnklMBChoHSZM17k0PBK+luePOLASbc+2ODlRJTEHCia/ycnlC2q0CeFItEkj+lKX6dmtN2HqnJ3hajVF6FGCXMTPNVp0MhdDRqD9qdx0rAjzDIBw0AEHUp7g03//ZjxUZUf7wqdUg/fPyvDcZfD52FtxhafvpXjQ7q+rXJqBzQj/Zi4T+006B7oYh4QTI9moh58JrOUSrjF8K41ynQZPWcaRKpF5KHc8VENWRCP9pKj6TIHAqT5IE+RrbDE7aZoa4e5T7ZzqjLz6i496dwarkrtPD2eUP0NMQ1eWhhHr+UtoD6QZ2FIxu7iZV5YdEYhM/M4S7wLp2ynMePTz+SRvdDEgnyDnKrWCPgDLvuK9c1C7iHVlB17xC0sgshVq8mRkD80n66FLjA3DMiT2pixPAZk54FVazWfHM1sSYF/kNk44xURBYcEaF5lZpJd3GzfAb2c5M6SbKCgwvXT/9A12ubT7A1Vm05tWeL8rqNm/+BsfI=
  distributions: sdist bdist_wheel
  skip_cleanup: true
  on:
    tags: true
    python: 2.7
